#!/bin/sh
# Gradle start up script for POSIX generated by Gradle
# Attempt to set APP_HOME
APP_HOME="$( cd ""${APP_HOME}"" .>/dev/null && pwd )"
exec "$APP_HOME/gradle/wrapper/gradle-wrapper.jar" "$@"